#ifndef COMMON_DEFINES_H
#define COMMON_DEFINES_H
#define RELEASE_NOTES "ICS-OS port"
#define MAX_UNDO_SLOTS 500
#define MAX_FILE_NAME 80
#define TEXT_BUFFER_SIZE 512
#define INPUT_BUFFER_SIZE 200
#define STACK_SIZE 1024
#define NO_BASENAME
#define NO_STRDUP
#define NO_STRNDUP
#define NO_SOUND
#define NO_BLORB
#endif /* COMMON_DEFINES_H */
