/* gen_engrave.c - host tool: emit NetHack's `engrave` random-text data file.
 *
 * This replicates, byte-for-byte, the exact logic of makedefs'
 * do_rnd_access_file(ENGRAVEFILE, deflt) for the engrave resource, so the
 * produced file has the same on-disk format as the other DLB random-text
 * entries (epitaph, bogusmon) that the game already reads successfully:
 *
 *   line 1:  Dont_Edit_Data header (skipped by get_rnd_text)
 *   line 2+: xcrypt()-obfuscated engraving phrases (one per line)
 *
 * xcrypt() and fgetline() are copied verbatim from util/makedefs.c.
 *
 * Usage: gen_engrave <engrave.txt> <out-engrave>
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* verbatim from util/makedefs.c */
static char *
xcrypt(str)
const char *str;
{
    static char buf[8192];
    register const char *p;
    register char *q;
    register int bitmask;

    for (bitmask = 1, p = str, q = buf; *p; q++) {
        *q = *p++;
        if (*q & (32 | 64))
            *q ^= bitmask;
        if ((bitmask <<= 1) >= 32)
            bitmask = 1;
    }
    *q = '\0';
    return buf;
}

/* verbatim from util/makedefs.c (includes trailing newline) */
static char *
fgetline(fd)
FILE *fd;
{
    static const int inc = 256;
    int len = inc;
    char *c = malloc(len), *ret;

    for (;;) {
        ret = fgets(c + len - inc, inc, fd);
        if (!ret) {
            free(c);
            c = NULL;
            break;
        } else if (index(c, '\n')) {
            break;
        }
        len += inc;
        c = realloc(c, len);
    }
    return c;
}

#define DONT_EDIT_DATA "#\tThis data file is generated by 'makedefs'.  Do not edit. \n"
#define ENGRAVE_DEFAULT "No matter where you go, there you are."

int
main(int argc, char **argv)
{
    FILE *ifp, *ofp;
    char *line;
    int nphrases = 0;

    if (argc != 3) {
        fprintf(stderr, "usage: %s <engrave.txt> <out-engrave>\n", argv[0]);
        return 2;
    }
    if (!(ifp = fopen(argv[1], "rb"))) {
        perror(argv[1]);
        return 1;
    }
    if (!(ofp = fopen(argv[2], "wb"))) {
        perror(argv[2]);
        fclose(ifp);
        return 1;
    }

    /* mirror do_rnd_access_file() exactly */
    fputs(DONT_EDIT_DATA, ofp);
    fputs(xcrypt(ENGRAVE_DEFAULT), ofp); /* no trailing newline (matches makedefs) */

    while ((line = fgetline(ifp)) != 0) {
        if (line[0] != '#' && line[0] != '\n') {
            fputs(xcrypt(line), ofp);
            nphrases++;
        }
        free(line);
    }
    fclose(ifp);
    fclose(ofp);

    /* self-check: prove xcrypt is an involution on a sample phrase */
    {
        const char *s = "Elbereth\n";
        char *once = xcrypt(s);
        char *twice = xcrypt(once);
        if (strcmp(twice, s) != 0) {
            fprintf(stderr, "INTERNAL: xcrypt not an involution\n");
            return 3;
        }
    }
    fprintf(stderr, "gen_engrave: wrote %s with %d phrases (+1 default)\n",
            argv[2], nphrases);
    return 0;
}
